
From: joemail@joeschedule.com
To: Frank Mastronardi <mastronardif@gmail.com>
Subject: test message joemailweb
MIME-Version: 1.0
Content-Type: text/html; charset="UTF-8"

<html>
<body>


Geetha, 
Unable to see it so far.

Good news for you were are in a great housing depression supposable.

<a 
href="mailto:joemail@joeschedule.com?subject=joemailweb&body=%26lt%3Btags%26gt%3Bhttp%3A%2F%2Fwww.cnbc.com%2Fid%2F43395857%26lt%3B%2Ftags%26gt%3B"> 
<font color="red">US Housing Crisis Now Worse Than Great Depression...</font>
</a>
<br/>
<br/>


>>listing for 6.. then ur home must be a very big one... wish u luck!
>>did u happen to see the place 20 south.. summit...



</body>    
</html>

<b>Thank you for using joemailweb.</b><hr></hr><br/>
<RTAGS>
<br/>
(http://www.i-programmer.info/professional-programmer/i-programmer/2591-dumping-net-microsofts-madness.html)
<br/>

<br/>
</RTAGS>
<br/>
<hr></hr>

